# Generated by Django 4.1 on 2022-12-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.CharField(max_length=100)),
                ('largest_city', models.CharField(max_length=100)),
                ('official_languages', models.CharField(max_length=100)),
                ('area_total', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=10)),
                ('GDP_nominal', models.CharField(max_length=10)),
            ],
        ),
    ]
